#!/system/bin/sh
# CFX perms
# set permissions needed for CFX features

# fast charge
if [ -e /sys/kernel/fast_charge/force_fast_charge ];
then
#   chmod 644 /sys/kernel/fast_charge/force_fast_charge
   chown system:system /sys/kernel/fast_charge/force_fast_charge
fi;
