#!/system/bin/sh
# EOS perms
# set permissions needed for EOS features

# O-touch
if [ -e /proc/touchpad/enable ];
then
   chown root:root /proc/touchpad/enable
   chmod 666 /proc/touchpad/enable
   chown system:system /proc/touchpad/enable
fi;
