#!/system/bin/sh

# set boot values for eos kernel controls

# ZRAM allocate 10% of device memory
# credit Imoseyon

if [ -e /data/data/org.eos.controlcenter/app_eos/zram_on_boot ]; then
    RAMSIZE=`grep MemTotal /proc/meminfo | awk '{ print \$2 }'`
    ZRAMSIZE=$(($RAMSIZE*100))

    echo $ZRAMSIZE > /sys/block/zram0/disksize && \
    /system/xbin/mkswap /dev/block/zram0 && \
    /system/xbin/swapon /dev/block/zram0 && \
    echo "500,1000,20000,20000,20000,25000" > /sys/module/lowmemorykiller/parameters/minfree
fi

# frequency control

files="/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq \
       /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq \
       /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq \
       /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq \
       /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor \
       /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor"

for x in $files; do
    chmod 664 $x
    chgrp system $x
done

if [ -e /data/data/org.eos.controlcenter/app_eos/clocks_on_boot ]; then
    thtt /data/local/eos_clocking
    TEST_VALUE=$?

    if [ ! $TEST_VALUE -eq 0 ]; then
        setprop eos.overclocking.failed 1
    fi;
fi

# I/O scheduler
chgrp system /sys/block/mmcblk0/queue/scheduler
chmod 664 /sys/block/mmcblk0/queue/scheduler

# Sweep2Wake if kernel supports it
if [ -e /sys/android_touch/sweep2wake ]; then
    chgrp system /sys/android_touch/sweep2wake
    chmod 664 /sys/android_touch/sweep2wake
fi

# USB fast charge, we just set perms. This is likely
# not something we want to set on boot
if [ -e /sys/kernel/fast_charge/force_fast_charge ]; then
    chgrp system /sys/kernel/fast_charge/force_fast_charge
    chmod 664 /sys/kernel/fast_charge/force_fast_charge
fi

# Support for secondary touchpads with a control
# interface in /proc/touchpad/enable
if [ -e /proc/touchpad/enable ]; then
    chown root:root /proc/touchpad/enable
    chmod 666 /proc/touchpad/enable
    chgrp system /proc/touchpad/enable
fi
