#!/system/bin/sh

chgrp system /sys/android_touch/sweep2wake
chmod 664 /sys/android_touch/sweep2wake

# s2w is enabled in the kernel by default
# so turn off by default
echo "0" > /sys/android_touch/sweep2wake

# bring it back if users want's it enabled on boot
if [ -e /data/data/org.eos.controlcenter/app_eos/s2w_on_boot ]; then
    echo "1" > /sys/android_touch/sweep2wake
fi;



