#!/system/bin/sh

chgrp system /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq  /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
chmod 664 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq  /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq

if [ -e /data/data/com.android.settings/app_eos/clocks_on_boot ]; then
    thtt /data/local/eos_clocking
    TEST_VALUE=$?

    if [ $TEST_VALUE -eq 0 ]; then
        if [ -e /data/data/com.android.settings/app_eos/clocks_min ]; then
            cat /data/data/com.android.settings/app_eos/clocks_min > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
            cat /data/data/com.android.settings/app_eos/clocks_min > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
        fi;

        if [ -e /data/data/com.android.settings/app_eos/clocks_max ]; then
            cat /data/data/com.android.settings/app_eos/clocks_max > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
            cat /data/data/com.android.settings/app_eos/clocks_max > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
        fi;

        if [ -e /data/data/com.android.settings/app_eos/clocks_gov ]; then
            cat /data/data/com.android.settings/app_eos/clocks_gov > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
            cat /data/data/com.android.settings/app_eos/clocks_gov > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
        fi;
    else
        setprop eos.overclocking.failed 1
    fi;
fi
